### ISSUE TITLE
部署遇到一个未知异常

### ISSUE THREAD

**Issue by telltime** [RickyHuo/hangout-output-clickhouse#15]
hangout使用的0.3版
ck插件0.7版
执行出现抛出未知异常

2018-12-07 14:08:18,768 [main] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka version : 0.9.0.1
2018-12-07 14:08:18,768 [main] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : 23c69d62a0cabf06
2018-12-07 14:08:18,768 [main] INFO  org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	group.id = cmcc
	partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	max.partition.fetch.bytes = 1048576
	bootstrap.servers = [127.0.0.1:9092]
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.keystore.type = JKS
	ssl.trustmanager.algorithm = PKIX
	enable.auto.commit = true
	ssl.key.password = null
	fetch.max.wait.ms = 500
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	ssl.truststore.password = null
	session.timeout.ms = 30000
	metrics.num.samples = 2
	client.id = 
	ssl.endpoint.identification.algorithm = null
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	ssl.protocol = TLS
	check.crcs = true
	request.timeout.ms = 40000
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.keystore.location = null
	heartbeat.interval.ms = 3000
	auto.commit.interval.ms = 5000
	receive.buffer.bytes = 32768
	ssl.cipher.suites = null
	ssl.truststore.type = JKS
	security.protocol = PLAINTEXT
	ssl.truststore.location = null
	ssl.keystore.password = null
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	fetch.min.bytes = 1
	send.buffer.bytes = 131072
	auto.offset.reset = latest

2018-12-07 14:08:18,773 [main] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka version : 0.9.0.1
2018-12-07 14:08:18,773 [main] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : 23c69d62a0cabf06
2018-12-07 14:08:18,775 [main] INFO  com.ctrip.ops.sysdev.baseplugin.BaseInput - begin to build output com.sina.bip.hangout.outputs.Clickhouse
2018-12-07 14:08:18,782 [main] INFO  com.ctrip.ops.sysdev.baseplugin.BaseInput - maybe a third party output plugin. try to build com.sina.bip.hangout.outputs.Clickhouse
2018-12-07 14:08:18,784 [main] INFO  com.ctrip.ops.sysdev.baseplugin.BaseInput - build output com.sina.bip.hangout.outputs.Clickhouse done
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.ctrip.ops.sysdev.baseplugin.BaseInput.lambda$null$0(BaseInput.java:95)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.ctrip.ops.sysdev.baseplugin.BaseInput.lambda$createOutputProcessors$1(BaseInput.java:78)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)

我的yml配置信息

- inputs:
- - NewKafka:
- topic:
- cmcc: 1
- codec: plain
- consumer_settings:
- bootstrap.servers: 127.0.0.1:9092
- value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
- key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
- group.id: cmcc
- outputs:
- - com.sina.bip.hangout.outputs.Clickhouse:
- host: 127.0.0.1:8123
- username: ctl
- password: 12345678
- database: test
- table: cmcc
- fields: ['message']
- bulk_size: 100

检查inputs部分配置没有问题，问题在outputs部分，ck库连接也是正常的。

**Comment by RickyHuo** [comment]
@telltime 乍看没问题， 可以加我微信一起查一下  chodomatte1994
